using System.Collections.Frozen;

namespace VeloBrawl.V2.VB24BXIM9CA.Auxiliary.Debug;

public static class DebugInfoCollector // v36
{
    /// <summary>
    ///     <para>MessageName = key</para>
    ///     MessageType = value[0], ServiceNodeType = value[1]
    /// </summary>
    public static readonly FrozenDictionary<string, (int, int)> PacketCollectorX;

    /// <summary>
    ///     <para>MessageType = key</para>
    ///     MessageName = value[0], ServiceNodeType = value[1]
    /// </summary>
    public static readonly FrozenDictionary<int, (string, int)> PacketCollectorY;

    /// <summary>
    ///     <para>CommandName = key</para>
    ///     CommandType = value
    /// </summary>
    public static readonly FrozenDictionary<string, int> CommandCollectorX;

    /// <summary>
    ///     <para>CommandType = key</para>
    ///     CommandName = value
    /// </summary>
    public static readonly FrozenDictionary<int, string> CommandCollectorY;

    static DebugInfoCollector()
    {
        PacketCollectorX = new Dictionary<string, (int, int)>
        {
            { "AskPlayerJWTokenMessage", (10055, 9) },
            { "ClientCryptoErrorMessage", (10099, 1) },
            { "ClientHelloMessage", (10100, 1) },
            { "TitanLoginMessage", (10101, 1) },
            { "LoginUsingSessionMessage", (10102, 1) },
            { "CreateAccountMessage", (10103, 1) },
            { "ClientCapabilitiesMessage", (10107, 1) },
            { "KeepAliveMessage", (10108, 1) },
            { "UdpCheckConnectionMessage", (10109, 1) },
            { "AnalyticEventMessage", (10110, 9) },
            { "AccountIdentifiersMessage", (10111, 1) },
            { "AuthenticationCheckMessage", (10112, 1) },
            { "SetDeviceTokenMessage", (10113, 1) },
            { "ResetAccountMessage", (10116, 9) },
            { "ReportUserMessage", (10117, 1) },
            { "AccountSwitchedMessage", (10118, 1) },
            { "ReportAllianceStreamMessage", (10119, 11) },
            { "UnlockAccountMessage", (10121, 1) },
            { "AppleBillingRequestMessage", (10150, 1) },
            { "GoogleBillingRequestMessage", (10151, 1) },
            { "TencentBillingRequestMessage", (10152, 1) },
            { "CafeBazaarBillingRequestMessage", (10153, 1) },
            { "KunlunBillingRequestMessage", (10159, 1) },
            { "BillingCancelledByClientMessage", (10160, 9) },
            { "ClientInfoMessage", (10177, 27) },
            { "ChangeAvatarNameMessage", (10212, 9) },
            { "GetAllianceInviteTokenMessage", (10309, 11) },
            { "AttributionEventMessage", (10321, 9) },
            { "CreateGameMessage", (10401, 4) },
            { "AcceptFriendMessage", (10501, 26) },
            { "AddFriendMessage", (10502, 26) },
            { "AskForAddableFriendsMessage", (10503, 1) },
            { "AskForFriendListMessage", (10504, 26) },
            { "RemoveFriendMessage", (10506, 26) },
            { "AddFriendByEmailMessage", (10507, 3) },
            { "AddFriendByAvatarNameAndCodeMessage", (10509, 3) },
            { "AskForPlayingGamecenterFriendsMessage", (10512, 26) },
            { "AskForPlayingFacebookFriendsMessage", (10513, 26) },
            { "AskForPlayingKakaoFriendsMessage", (10514, 26) },
            { "AskForPlayingTencentFriendsMessage", (10515, 26) },
            { "AskForPlayingLineFriendsMessage", (10516, 26) },
            { "AskForPlayingSupercellFriendsMessage", (10517, 26) },
            { "YoozooBillingRequestMessage", (10523, 1) },
            { "ClientInputMessage", (10555, 27) },
            { "SetBlockFriendRequestsMessage", (10576, 26) },
            { "AskForFriendSuggestionsMessage", (10599, 26) },
            { "SCIDBindAccountMessage", (10636, 1) },
            { "SCIDLogoutAllDevicesMessage", (11736, 1) },
            { "CreatePlayerMapMessage", (12100, 9) },
            { "DeletePlayerMapMessage", (12101, 9) },
            { "GetPlayerMapsMessage", (12102, 9) },
            { "UpdatePlayerMapMessage", (12103, 9) },
            { "SubmitPlayerMapMessage", (12104, 9) },
            { "PublishPlayerMapMessage", (12105, 9) },
            { "ChangePlayerMapNameMessage", (12106, 9) },
            { "EnterMapEditorMessage", (12107, 9) },
            { "GoHomeFromMapEditorMessage", (12108, 9) },
            { "TeamSetPlayerMapMessage", (12110, 9) },
            { "SignoffPlayerMapMessage", (12111, 9) },
            { "ReportPlayerMapMessage", (12125, 9) },
            { "RankedMatchBanHeroMessage", (12152, 57) },
            { "RankedMatchPickHeroMessage", (12155, 9) },
            { "RankedMatchUpdateHeroDataMessage", (12157, 9) },
            { "GetCurrentBattleReplayDataMessage", (12905, 27) },
            { "SetCountryMessage", (12998, 9) },
            { "AcceptTokenFriendMessage", (13922, 26) },
            { "GoHomeMessage", (14101, 27) },
            { "EndClientTurnMessage", (14102, 9) },
            { "MatchmakeRequestMessage", (14103, 9) },
            { "StartGameMessage", (14103, 9) },
            { "StartSpectateMessage", (14104, 9) },
            { "StartMissionMessage", (14104, 9) },
            { "HomeLogicStoppedMessage", (14105, 9) },
            { "CancelMatchmakingMessage", (14106, 7) },
            { "StopSpectateMessage", (14107, 9) },
            { "GoHomeFromSpectateMessage", (14108, 9) },
            { "GoHomeFromOfflinePractiseMessage", (14109, 9) },
            { "AskForBattleEndMessage", (14110, 9) },
            { "GetPlayerProfileMessage", (14113, 9) },
            { "GetBattleLogMessage", (14114, 9) },
            { "HomeBattleReplayMessage", (14114, 9) },
            { "BattleLogViewReplayMessage", (14115, 9) },
            { "ViewReplayByStringIdMessage", (14116, 9) },
            { "RequestMatchCancelMessage", (14117, 27) },
            { "SinglePlayerMatchRequestMessage", (14118, 9) },
            { "ChronosEventSeenMessage", (14166, 9) },
            { "PlayAgainMessage", (14177, 27) },
            { "DebugCommandMessage", (14178, 27) },
            { "LookForGameRoomRequestMessage", (14199, 9) },
            { "BindFacebookAccountMessage", (14201, 1) },
            { "BindKakaoAccountMessage", (14202, 1) },
            { "BindLineAccountMessage", (14203, 1) },
            { "UnbindFacebookAccountMessage", (14211, 30) },
            { "BindGamecenterAccountMessage", (14212, 1) },
            { "UnbindKakaoAccountMessage", (14213, 30) },
            { "UnbindLineAccountMessage", (14214, 30) },
            { "BindGoogleServiceAccountMessage", (14262, 1) },
            { "BindYoozooAccountMessage", (14266, 1) },
            { "BindTencentAccountMessage", (14266, 1) },
            { "TencentAntiAddictionInstructionExecutedMessage", (14267, 1) },
            { "TencentCheckCanPayMessage", (14268, 1) },
            { "GetSeasonRewardsMessage", (14277, 9) },
            { "SetAllianceCountryMessage", (14299, 11) },
            { "CreateAllianceMessage", (14301, 9) },
            { "AskForAllianceDataMessage", (14302, 11) },
            { "AskForJoinableAlliancesListMessage", (14303, 9) },
            { "AskForAllianceStreamMessage", (14304, 11) },
            { "JoinAllianceMessage", (14305, 9) },
            { "ChangeAllianceMemberRoleMessage", (14306, 11) },
            { "KickAllianceMemberMessage", (14307, 11) },
            { "LeaveAllianceMessage", (14308, 11) },
            { "ChatToAllianceStreamMessage", (14315, 11) },
            { "ChangeAllianceSettingsMessage", (14316, 11) },
            { "RequestJoinAllianceMessage", (14317, 9) },
            { "RespondToAllianceJoinRequestMessage", (14321, 11) },
            { "SendAllianceInvitationMessage", (14322, 11) },
            { "JoinAllianceUsingInvitationMessage", (14323, 9) },
            { "SearchAlliancesMessage", (14324, 11) },
            { "SendAllianceInvitationToFriendMessage", (14326, 26) },
            { "SendAllianceMailMessage", (14330, 11) },
            { "TeamCreateMessage", (14350, 9) },
            { "TeamJoinMessage", (14351, 9) },
            { "TeamKickMessage", (14352, 23) },
            { "TeamLeaveMessage", (14353, 23) },
            { "TeamChangeMemberSettingsMessage", (14354, 9) },
            { "TeamSetMemberReadyMessage", (14355, 9) },
            { "TeamTogglePractiseMessage", (14356, 23) },
            { "TeamToggleMemberSideMessage", (14357, 23) },
            { "TeamSpectateMessage", (14358, 9) },
            { "TeamChatMessage", (14359, 23) },
            { "TeamPostAdMessage", (14360, 23) },
            { "TeamMemberStatusMessage", (14361, 23) },
            { "TeamSetEventMessage", (14362, 23) },
            { "TeamSetLocationMessage", (14363, 23) },
            { "TeamReportChatMessage", (14364, 23) },
            { "TeamInviteMessage", (14365, 26) },
            { "PlayerStatusMessage", (14366, 9) },
            { "TeamClearInviteMessage", (14367, 23) },
            { "TeamInviteResponseMessage", (14368, 23) },
            { "TeamPremadeChatMessage", (14369, 23) },
            { "TeamAllianceMemberInviteMessage", (14370, 11) },
            { "TeamJoinOrCreateRoomMessage", (14371, 9) },
            { "TeamToggleSettingsMessage", (14372, 23) },
            { "TeamBotSlotDisableMessage", (14373, 23) },
            { "GetLeaderboardMessage", (14403, 9) },
            { "AskForAvatarStreamMessage", (14405, 9) },
            { "AskForBattleReplayStreamMessage", (14406, 9) },
            { "RemoveAvatarStreamEntryMessage", (14418, 9) },
            { "TeamInvitationResponseMessage", (14479, 9) },
            { "AvatarNameCheckRequestMessage", (14600, 9) },
            { "ListBrawlTvChannelsMessage", (14700, 33) },
            { "TuneBrawlTvChannelMessage", (14701, 33) },
            { "SendGlobalChatLineMessage", (14715, 6) },
            { "SetInvitesBlockedMessage", (14777, 9) },
            { "SetTeamChatMutedMessage", (14778, 9) },
            { "SetRegionMessage", (14867, 9) },
            { "TeamRequestJoinCancelMessage", (14880, 9) },
            { "TeamRequestJoinMessage", (14881, 9) },
            { "TeamRequestJoinApproveMessage", (14882, 23) },
            { "GetTokenFriendMessage", (15793, 26) },
            { "LogicDeviceLinkCodeRequestMessage", (16000, 9) },
            { "LogicDeviceLinkMenuClosedMessage", (16001, 1) },
            { "LogicDeviceLinkEnterCodeMessage", (16002, 9) },
            { "LogicDeviceLinkConfirmYesMessage", (16003, 1) },
            { "AskApiTokenMessage", (16939, 9) },
            { "LogicAccountTransferCodeRequestMessage", (17000, 9) },
            { "JoinAllianceUsingTokenMessage", (17190, 9) },
            { "UnbotifyReportMessage", (17337, 9) },
            { "AdjustPackageMessage", (17338, 9) },
            { "SetSupportedCreatorMessage", (18686, 9) },
            { "LatencyTestResultMessage", (19001, 9) },
            { "UdpLatencyTestRequestMessage", (19002, 9) },
            { "TriggerStartLatencyTestMessage", (19003, 9) },
            { "RequestLatencyTestStatusMessage", (19004, 9) },
            { "SetEncryptionMessage", (20000, 1) },
            { "ServerHelloMessage", (20100, 1) },
            { "CreateAccountOkMessage", (20101, 1) },
            { "CreateAccountFailedMessage", (20101, 1) },
            { "UdpBigMessageFragmentMessage", (20101, 27) },
            { "TitanLoginFailedMessage", (20103, 1) },
            { "LoginOkMessage", (20104, 1) },
            { "AuthenticationResponseMessage", (20104, 1) },
            { "FriendListMessage", (20105, 3) },
            { "FriendListUpdateMessage", (20106, 26) },
            { "AddableFriendsMessage", (20107, 26) },
            { "KeepAliveServerMessage", (20108, 1) },
            { "FriendOnlineStatusMessage", (20109, 3) },
            { "FriendLoggedInMessage", (20110, 9) },
            { "FriendLoggedOutMessage", (20111, 9) },
            { "AddFriendFailedMessage", (20112, 1) },
            { "ReportUserStatusMessage", (20117, 1) },
            { "ChatAccountBanStatusMessage", (20118, 1) },
            { "BillingRequestFailedMessage", (20121, 1) },
            { "UnlockAccountOkMessage", (20132, 1) },
            { "UnlockAccountFailedMessage", (20133, 1) },
            { "AppleBillingProcessedByServerMessage", (20151, 1) },
            { "GoogleBillingProcessedByServerMessage", (20152, 1) },
            { "TencentBillingProcessedByServerMessage", (20153, 1) },
            { "CafeBazaarBillingProcessedByServerMessage", (20154, 1) },
            { "KunlunBillingProcessedByServerMessage", (20156, 1) },
            { "ShutdownStartedMessage", (20161, 1) },
            { "PersonalBreakStartedMessage", (20171, 1) },
            { "YoozooBillingProcessedByServerMessage", (20173, 1) },
            { "FriendSuggestionsMessage", (20199, 26) },
            { "AvatarNameChangeFailedMessage", (20205, 9) },
            { "AvatarOnlineStatusUpdated", (20206, 9) },
            { "AllianceOnlineStatusUpdatedMessage", (20207, 9) },
            { "AvatarNameCheckResponseMessage", (20300, 9) },
            { "CreateGameFailedMessage", (20402, 4) },
            { "MatchMakingStatusMessage", (20405, 4) },
            { "MatchMakingCancelledMessage", (20406, 4) },
            { "AcceptFriendFailedMessage", (20501, 26) },
            { "YoozooOrderAvailableMessage", (20523, 1) },
            { "YoozooOrderDeliveryFailedMessage", (20545, 1) },
            { "StartLoadingMessage", (20559, 4) },
            { "NotificationMessage", (20801, 9) },
            { "AntiAddictionDataUpdatedMessage", (20931, 1) },
            { "GetTokenFriendResultMessage", (22089, 26) },
            { "CreatePlayerMapResponseMessage", (22100, 9) },
            { "DeletePlayerMapResponseMessage", (22101, 9) },
            { "PlayerMapsMessage", (22102, 9) },
            { "UpdatePlayerMapResponseMessage", (22103, 9) },
            { "SubmitPlayerMapResponseMessage", (22104, 9) },
            { "PublishPlayerMapResponseMessage", (22105, 9) },
            { "ChangePlayerMapNameResponseMessage", (22106, 9) },
            { "PlayerMapInfoUpdatedMessage", (22107, 9) },
            { "DebugPlayerMapReviewResultOverrideSetMessage", (22109, 9) },
            { "PlayerMapGreenlightedMessage", (22111, 9) },
            { "ReportPlayerMapResponseMessage", (22125, 9) },
            { "RankedMatchStartedMessage", (22150, 9) },
            { "RankedMatchBanStartedMessage", (22151, 57) },
            { "RankedMatchBanHeroResponseMessage", (22152, 57) },
            { "RankedMatchBanEndedMessage", (22153, 57) },
            { "RankedMatchPickStartedMessage", (22154, 57) },
            { "RankedMatchPickHeroFailedMessage", (22155, 57) },
            { "RankedMatchHeroPickedMessage", (22156, 57) },
            { "RankedMatchHeroDataUpdatedMessage", (22157, 57) },
            { "RankedMatchFinalPreparationStartedMessage", (22158, 57) },
            { "RankedMatchTerminatedMessage", (22159, 9) },
            { "MapPreviewMessage", (22202, 9) },
            { "GoogleServiceAccountBoundMessage", (22377, 10) },
            { "GamecenterAccountAlreadyBoundMessage", (22687, 1) },
            { "PvpMatchmakeNotificationMessage", (22957, 9) },
            { "SCIDLogoutAllDevicesResultMessage", (23067, 1) },
            { "GetAllianceInviteTokenResultMessage", (23302, 26) },
            { "BattleEndMessage", (23456, 27) },
            { "LobbyInfoMessage", (23457, 27) },
            { "BattleLogMessage", (23458, 9) },
            { "BattleLogReplayAvailableMessage", (23459, 9) },
            { "GoogleServiceAccountAlreadyBoundMessage", (23494, 1) },
            { "PlayerJWTokenMessage", (23774, 9) },
            { "OwnHomeDataMessage", (24101, 9) },
            { "OutOfSyncMessage", (24104, 9) },
            { "SpectateFailedMessage", (24105, 9) },
            { "StopHomeLogicMessage", (24106, 9) },
            { "MatchmakeFailedMessage", (24108, 9) },
            { "VisionUpdateMessage", (24109, 4) },
            { "AvailableServerCommandMessage", (24111, 9) },
            { "UdpConnectionInfoMessage", (24112, 27) },
            { "PlayerProfileMessage", (24113, 9) },
            { "HomeBattleReplayDataMessage", (24114, 9) },
            { "ServerErrorMessage", (24115, 9) },
            { "DebugNewbieCoopOverrideSetMessage", (24116, 9) },
            { "HomeBattleReplayFailedMessage", (24116, 9) },
            { "HomeBattleReplayViewedMessage", (24117, 9) },
            { "DailyEventsMessage", (24123, 9) },
            { "SeasonRewardsMessage", (24123, 9) },
            { "TeamMessage", (24124, 9) },
            { "TeamLeftMessage", (24125, 9) },
            { "TeamErrorMessage", (24129, 9) },
            { "TeamGameStartingMessage", (24130, 9) },
            { "TeamStreamMessage", (24131, 11) },
            { "SetRegionResponseMessage", (24177, 9) },
            { "SetCountryResponseMessage", (24178, 9) },
            { "FacebookAccountBoundMessage", (24201, 9) },
            { "FacebookAccountAlreadyBoundMessage", (24202, 1) },
            { "KakaoAccountBoundMessage", (24203, 9) },
            { "KakaoAccountAlreadyBoundMessage", (24204, 1) },
            { "LineAccountAlreadyBoundMessage", (24205, 1) },
            { "LineAccountBoundMessage", (24206, 9) },
            { "FacebookAccountUnboundMessage", (24214, 9) },
            { "KakaoAccountUnboundMessage", (24215, 9) },
            { "LineAccountUnboundMessage", (24216, 9) },
            { "TencentAccountBoundMessage", (24220, 9) },
            { "TencentAccountAlreadyBoundMessage", (24221, 1) },
            { "TencentAntiAddictionInstructionMessage", (24222, 1) },
            { "TencentCheckCanPayResponseMessage", (24223, 1) },
            { "AllianceDataMessage", (24301, 11) },
            { "JoinableAllianceListMessage", (24304, 11) },
            { "AllianceMemberMessage", (24308, 11) },
            { "AllianceMemberRemovedMessage", (24309, 11) },
            { "AllianceListMessage", (24310, 11) },
            { "AllianceStreamMessage", (24311, 11) },
            { "AllianceStreamEntryMessage", (24312, 11) },
            { "ChangeAllianceSettingsOkMessage", (24313, 11) },
            { "AllianceStreamEntryRemovedMessage", (24318, 11) },
            { "TeamStreamEntryRemovedMessage", (24319, 11) },
            { "AllianceInvitationSendFailedMessage", (24321, 11) },
            { "AllianceResponseMessage", (24333, 11) },
            { "AllianceTeamsMessage", (24364, 11) },
            { "AllianceTeamRemovedMessage", (24365, 11) },
            { "MyAllianceMessage", (24399, 11) },
            { "LeaderboardMessage", (24403, 13) },
            { "AvatarStreamMessage", (24411, 11) },
            { "AvatarStreamEntryMessage", (24412, 11) },
            { "BattleReportStreamMessage", (24413, 11) },
            { "AvatarStreamEntryRemovedMessage", (24418, 11) },
            { "FriendOnlineStatusEntryMessage", (24555, 11) },
            { "TeamInviteStatusMessage", (24582, 23) },
            { "TeamInvitationMessage", (24589, 9) },
            { "BrawlTvChannelListMessage", (24700, 33) },
            { "BrawlTvChannelNextUpMessage", (24701, 33) },
            { "GlobalChatLineMessage", (24715, 6) },
            { "ApiTokenMessage", (24758, 9) },
            { "AllianceWarMessage", (24776, 25) },
            { "PlayAgainStatusMessage", (24777, 9) },
            { "SCIDAccountBoundMessage", (25165, 10) },
            { "DisconnectedMessage", (25892, 1) },
            { "TitanDisconnectedMessage", (25892, 1) },
            { "LogicDeviceLinkCodeResponseMessage", (26002, 1) },
            { "LogicDeviceLinkNewDeviceLinkedMessage", (26003, 1) },
            { "LogicDeviceLinkCodeDeactivatedMessage", (26004, 1) },
            { "LogicDeviceLinkResponseMessage", (26005, 1) },
            { "LogicDeviceLinkDoneMessage", (26007, 1) },
            { "LogicDeviceLinkErrorMessage", (26008, 1) },
            { "GamecenterAccountBoundMessage", (26085, 10) },
            { "LogicAccountTransferCodeResponseMessage", (27002, 1) },
            { "BuyBundleBillingPackResponseMessage", (28363, 9) },
            { "SetSupportedCreatorResponseMessage", (28686, 9) },
            { "SCIDAccountAlreadyBoundMessage", (28689, 1) },
            { "StartLatencyTestRequestMessage", (29001, 9) },
            { "UdpLatencyTestResponseMessage", (29002, 9) },
            { "LatencyTestStatusMessage", (29003, 9) },
            { "SupercellIdNotificationMessage", (29900, 9) },
            { "CryptoErrorMessage", (29997, 1) },
            { "AttributionMessage", (30000, 9) },
            { "AdUpdateConversionValueMessage", (40000, 1) },
            { "LoginMessage", (10101, 1) },
            { "LoginFailedMessage", (20103, 1) },
            { "FriendAvatarBaseMessage", (0, 26) }
        }.ToFrozenDictionary();

        PacketCollectorY = new Dictionary<int, (string, int)>
        {
            { 10055, ("AskPlayerJWTokenMessage", 9) },
            { 10099, ("ClientCryptoErrorMessage", 1) },
            { 10100, ("ClientHelloMessage", 1) },
            { 10101, ("TitanLoginMessage", 1) },
            { 10102, ("LoginUsingSessionMessage", 1) },
            { 10103, ("CreateAccountMessage", 1) },
            { 10107, ("ClientCapabilitiesMessage", 1) },
            { 10108, ("KeepAliveMessage", 1) },
            { 10109, ("UdpCheckConnectionMessage", 1) },
            { 10110, ("AnalyticEventMessage", 9) },
            { 10111, ("AccountIdentifiersMessage", 1) },
            { 10112, ("AuthenticationCheckMessage", 1) },
            { 10113, ("SetDeviceTokenMessage", 1) },
            { 10116, ("ResetAccountMessage", 9) },
            { 10117, ("ReportUserMessage", 1) },
            { 10118, ("AccountSwitchedMessage", 1) },
            { 10119, ("ReportAllianceStreamMessage", 11) },
            { 10121, ("UnlockAccountMessage", 1) },
            { 10150, ("AppleBillingRequestMessage", 1) },
            { 10151, ("GoogleBillingRequestMessage", 1) },
            { 10152, ("TencentBillingRequestMessage", 1) },
            { 10153, ("CafeBazaarBillingRequestMessage", 1) },
            { 10159, ("KunlunBillingRequestMessage", 1) },
            { 10160, ("BillingCancelledByClientMessage", 9) },
            { 10177, ("ClientInfoMessage", 27) },
            { 10212, ("ChangeAvatarNameMessage", 9) },
            { 10309, ("GetAllianceInviteTokenMessage", 11) },
            { 10321, ("AttributionEventMessage", 9) },
            { 10401, ("CreateGameMessage", 4) },
            { 10501, ("AcceptFriendMessage", 26) },
            { 10502, ("AddFriendMessage", 26) },
            { 10503, ("AskForAddableFriendsMessage", 1) },
            { 10504, ("AskForFriendListMessage", 26) },
            { 10506, ("RemoveFriendMessage", 26) },
            { 10507, ("AddFriendByEmailMessage", 3) },
            { 10509, ("AddFriendByAvatarNameAndCodeMessage", 3) },
            { 10512, ("AskForPlayingGamecenterFriendsMessage", 26) },
            { 10513, ("AskForPlayingFacebookFriendsMessage", 26) },
            { 10514, ("AskForPlayingKakaoFriendsMessage", 26) },
            { 10515, ("AskForPlayingTencentFriendsMessage", 26) },
            { 10516, ("AskForPlayingLineFriendsMessage", 26) },
            { 10517, ("AskForPlayingSupercellFriendsMessage", 26) },
            { 10523, ("YoozooBillingRequestMessage", 1) },
            { 10555, ("ClientInputMessage", 27) },
            { 10576, ("SetBlockFriendRequestsMessage", 26) },
            { 10599, ("AskForFriendSuggestionsMessage", 26) },
            { 10636, ("SCIDBindAccountMessage", 1) },
            { 11736, ("SCIDLogoutAllDevicesMessage", 1) },
            { 12100, ("CreatePlayerMapMessage", 9) },
            { 12101, ("DeletePlayerMapMessage", 9) },
            { 12102, ("GetPlayerMapsMessage", 9) },
            { 12103, ("UpdatePlayerMapMessage", 9) },
            { 12104, ("SubmitPlayerMapMessage", 9) },
            { 12105, ("PublishPlayerMapMessage", 9) },
            { 12106, ("ChangePlayerMapNameMessage", 9) },
            { 12107, ("EnterMapEditorMessage", 9) },
            { 12108, ("GoHomeFromMapEditorMessage", 9) },
            { 12110, ("TeamSetPlayerMapMessage", 9) },
            { 12111, ("SignoffPlayerMapMessage", 9) },
            { 12125, ("ReportPlayerMapMessage", 9) },
            { 12152, ("RankedMatchBanHeroMessage", 57) },
            { 12155, ("RankedMatchPickHeroMessage", 9) },
            { 12157, ("RankedMatchUpdateHeroDataMessage", 9) },
            { 12905, ("GetCurrentBattleReplayDataMessage", 27) },
            { 12998, ("SetCountryMessage", 9) },
            { 13922, ("AcceptTokenFriendMessage", 26) },
            { 14101, ("GoHomeMessage", 27) },
            { 14102, ("EndClientTurnMessage", 9) },
            { 14103, ("StartGameMessage", 9) },
            { 14104, ("StartMissionMessage", 9) },
            { 14105, ("HomeLogicStoppedMessage", 9) },
            { 14106, ("CancelMatchmakingMessage", 7) },
            { 14107, ("StopSpectateMessage", 9) },
            { 14108, ("GoHomeFromSpectateMessage", 9) },
            { 14109, ("GoHomeFromOfflinePractiseMessage", 9) },
            { 14110, ("AskForBattleEndMessage", 9) },
            { 14113, ("GetPlayerProfileMessage", 9) },
            { 14114, ("HomeBattleReplayMessage", 9) },
            { 14115, ("BattleLogViewReplayMessage", 9) },
            { 14116, ("ViewReplayByStringIdMessage", 9) },
            { 14117, ("RequestMatchCancelMessage", 27) },
            { 14118, ("SinglePlayerMatchRequestMessage", 9) },
            { 14166, ("ChronosEventSeenMessage", 9) },
            { 14177, ("PlayAgainMessage", 27) },
            { 14178, ("DebugCommandMessage", 27) },
            { 14199, ("LookForGameRoomRequestMessage", 9) },
            { 14201, ("BindFacebookAccountMessage", 1) },
            { 14202, ("BindKakaoAccountMessage", 1) },
            { 14203, ("BindLineAccountMessage", 1) },
            { 14211, ("UnbindFacebookAccountMessage", 30) },
            { 14212, ("BindGamecenterAccountMessage", 1) },
            { 14213, ("UnbindKakaoAccountMessage", 30) },
            { 14214, ("UnbindLineAccountMessage", 30) },
            { 14262, ("BindGoogleServiceAccountMessage", 1) },
            { 14266, ("BindTencentAccountMessage", 1) },
            { 14267, ("TencentAntiAddictionInstructionExecutedMessage", 1) },
            { 14268, ("TencentCheckCanPayMessage", 1) },
            { 14277, ("GetSeasonRewardsMessage", 9) },
            { 14299, ("SetAllianceCountryMessage", 11) },
            { 14301, ("CreateAllianceMessage", 9) },
            { 14302, ("AskForAllianceDataMessage", 11) },
            { 14303, ("AskForJoinableAlliancesListMessage", 9) },
            { 14304, ("AskForAllianceStreamMessage", 11) },
            { 14305, ("JoinAllianceMessage", 9) },
            { 14306, ("ChangeAllianceMemberRoleMessage", 11) },
            { 14307, ("KickAllianceMemberMessage", 11) },
            { 14308, ("LeaveAllianceMessage", 11) },
            { 14315, ("ChatToAllianceStreamMessage", 11) },
            { 14316, ("ChangeAllianceSettingsMessage", 11) },
            { 14317, ("RequestJoinAllianceMessage", 9) },
            { 14321, ("RespondToAllianceJoinRequestMessage", 11) },
            { 14322, ("SendAllianceInvitationMessage", 11) },
            { 14323, ("JoinAllianceUsingInvitationMessage", 9) },
            { 14324, ("SearchAlliancesMessage", 11) },
            { 14326, ("SendAllianceInvitationToFriendMessage", 26) },
            { 14330, ("SendAllianceMailMessage", 11) },
            { 14350, ("TeamCreateMessage", 9) },
            { 14351, ("TeamJoinMessage", 9) },
            { 14352, ("TeamKickMessage", 23) },
            { 14353, ("TeamLeaveMessage", 23) },
            { 14354, ("TeamChangeMemberSettingsMessage", 9) },
            { 14355, ("TeamSetMemberReadyMessage", 9) },
            { 14356, ("TeamTogglePractiseMessage", 23) },
            { 14357, ("TeamToggleMemberSideMessage", 23) },
            { 14358, ("TeamSpectateMessage", 9) },
            { 14359, ("TeamChatMessage", 23) },
            { 14360, ("TeamPostAdMessage", 23) },
            { 14361, ("TeamMemberStatusMessage", 23) },
            { 14362, ("TeamSetEventMessage", 23) },
            { 14363, ("TeamSetLocationMessage", 23) },
            { 14364, ("TeamReportChatMessage", 23) },
            { 14365, ("TeamInviteMessage", 26) },
            { 14366, ("PlayerStatusMessage", 9) },
            { 14367, ("TeamClearInviteMessage", 23) },
            { 14368, ("TeamInviteResponseMessage", 23) },
            { 14369, ("TeamPremadeChatMessage", 23) },
            { 14370, ("TeamAllianceMemberInviteMessage", 11) },
            { 14371, ("TeamJoinOrCreateRoomMessage", 9) },
            { 14372, ("TeamToggleSettingsMessage", 23) },
            { 14373, ("TeamBotSlotDisableMessage", 23) },
            { 14403, ("GetLeaderboardMessage", 9) },
            { 14405, ("AskForAvatarStreamMessage", 9) },
            { 14406, ("AskForBattleReplayStreamMessage", 9) },
            { 14418, ("RemoveAvatarStreamEntryMessage", 9) },
            { 14479, ("TeamInvitationResponseMessage", 9) },
            { 14600, ("AvatarNameCheckRequestMessage", 9) },
            { 14700, ("ListBrawlTvChannelsMessage", 33) },
            { 14701, ("TuneBrawlTvChannelMessage", 33) },
            { 14715, ("SendGlobalChatLineMessage", 6) },
            { 14777, ("SetInvitesBlockedMessage", 9) },
            { 14778, ("SetTeamChatMutedMessage", 9) },
            { 14867, ("SetRegionMessage", 9) },
            { 14880, ("TeamRequestJoinCancelMessage", 9) },
            { 14881, ("TeamRequestJoinMessage", 9) },
            { 14882, ("TeamRequestJoinApproveMessage", 23) },
            { 15793, ("GetTokenFriendMessage", 26) },
            { 16000, ("LogicDeviceLinkCodeRequestMessage", 9) },
            { 16001, ("LogicDeviceLinkMenuClosedMessage", 1) },
            { 16002, ("LogicDeviceLinkEnterCodeMessage", 9) },
            { 16003, ("LogicDeviceLinkConfirmYesMessage", 1) },
            { 16939, ("AskApiTokenMessage", 9) },
            { 17000, ("LogicAccountTransferCodeRequestMessage", 9) },
            { 17190, ("JoinAllianceUsingTokenMessage", 9) },
            { 17337, ("UnbotifyReportMessage", 9) },
            { 17338, ("AdjustPackageMessage", 9) },
            { 18686, ("SetSupportedCreatorMessage", 9) },
            { 19001, ("LatencyTestResultMessage", 9) },
            { 19002, ("UdpLatencyTestRequestMessage", 9) },
            { 19003, ("TriggerStartLatencyTestMessage", 9) },
            { 19004, ("RequestLatencyTestStatusMessage", 9) },
            { 20000, ("SetEncryptionMessage", 1) },
            { 20100, ("ServerHelloMessage", 1) },
            { 20101, ("UdpBigMessageFragmentMessage", 27) },
            { 20103, ("TitanLoginFailedMessage", 1) },
            { 20104, ("AuthenticationResponseMessage", 1) },
            { 20105, ("FriendListMessage", 3) },
            { 20106, ("FriendListUpdateMessage", 26) },
            { 20107, ("AddableFriendsMessage", 26) },
            { 20108, ("KeepAliveServerMessage", 1) },
            { 20109, ("FriendOnlineStatusMessage", 3) },
            { 20110, ("FriendLoggedInMessage", 9) },
            { 20111, ("FriendLoggedOutMessage", 9) },
            { 20112, ("AddFriendFailedMessage", 1) },
            { 20117, ("ReportUserStatusMessage", 1) },
            { 20118, ("ChatAccountBanStatusMessage", 1) },
            { 20121, ("BillingRequestFailedMessage", 1) },
            { 20132, ("UnlockAccountOkMessage", 1) },
            { 20133, ("UnlockAccountFailedMessage", 1) },
            { 20151, ("AppleBillingProcessedByServerMessage", 1) },
            { 20152, ("GoogleBillingProcessedByServerMessage", 1) },
            { 20153, ("TencentBillingProcessedByServerMessage", 1) },
            { 20154, ("CafeBazaarBillingProcessedByServerMessage", 1) },
            { 20156, ("KunlunBillingProcessedByServerMessage", 1) },
            { 20161, ("ShutdownStartedMessage", 1) },
            { 20171, ("PersonalBreakStartedMessage", 1) },
            { 20173, ("YoozooBillingProcessedByServerMessage", 1) },
            { 20199, ("FriendSuggestionsMessage", 26) },
            { 20205, ("AvatarNameChangeFailedMessage", 9) },
            { 20206, ("AvatarOnlineStatusUpdated", 9) },
            { 20207, ("AllianceOnlineStatusUpdatedMessage", 9) },
            { 20300, ("AvatarNameCheckResponseMessage", 9) },
            { 20402, ("CreateGameFailedMessage", 4) },
            { 20405, ("MatchMakingStatusMessage", 4) },
            { 20406, ("MatchMakingCancelledMessage", 4) },
            { 20501, ("AcceptFriendFailedMessage", 26) },
            { 20523, ("YoozooOrderAvailableMessage", 1) },
            { 20545, ("YoozooOrderDeliveryFailedMessage", 1) },
            { 20559, ("StartLoadingMessage", 4) },
            { 20801, ("NotificationMessage", 9) },
            { 20931, ("AntiAddictionDataUpdatedMessage", 1) },
            { 22089, ("GetTokenFriendResultMessage", 26) },
            { 22100, ("CreatePlayerMapResponseMessage", 9) },
            { 22101, ("DeletePlayerMapResponseMessage", 9) },
            { 22102, ("PlayerMapsMessage", 9) },
            { 22103, ("UpdatePlayerMapResponseMessage", 9) },
            { 22104, ("SubmitPlayerMapResponseMessage", 9) },
            { 22105, ("PublishPlayerMapResponseMessage", 9) },
            { 22106, ("ChangePlayerMapNameResponseMessage", 9) },
            { 22107, ("PlayerMapInfoUpdatedMessage", 9) },
            { 22109, ("DebugPlayerMapReviewResultOverrideSetMessage", 9) },
            { 22111, ("PlayerMapGreenlightedMessage", 9) },
            { 22125, ("ReportPlayerMapResponseMessage", 9) },
            { 22150, ("RankedMatchStartedMessage", 9) },
            { 22151, ("RankedMatchBanStartedMessage", 57) },
            { 22152, ("RankedMatchBanHeroResponseMessage", 57) },
            { 22153, ("RankedMatchBanEndedMessage", 57) },
            { 22154, ("RankedMatchPickStartedMessage", 57) },
            { 22155, ("RankedMatchPickHeroFailedMessage", 57) },
            { 22156, ("RankedMatchHeroPickedMessage", 57) },
            { 22157, ("RankedMatchHeroDataUpdatedMessage", 57) },
            { 22158, ("RankedMatchFinalPreparationStartedMessage", 57) },
            { 22159, ("RankedMatchTerminatedMessage", 9) },
            { 22202, ("MapPreviewMessage", 9) },
            { 22377, ("GoogleServiceAccountBoundMessage", 10) },
            { 22687, ("GamecenterAccountAlreadyBoundMessage", 1) },
            { 22957, ("PvpMatchmakeNotificationMessage", 9) },
            { 23067, ("SCIDLogoutAllDevicesResultMessage", 1) },
            { 23302, ("GetAllianceInviteTokenResultMessage", 26) },
            { 23456, ("BattleEndMessage", 27) },
            { 23457, ("LobbyInfoMessage", 27) },
            { 23458, ("BattleLogMessage", 9) },
            { 23459, ("BattleLogReplayAvailableMessage", 9) },
            { 23494, ("GoogleServiceAccountAlreadyBoundMessage", 1) },
            { 23774, ("PlayerJWTokenMessage", 9) },
            { 24101, ("OwnHomeDataMessage", 9) },
            { 24104, ("OutOfSyncMessage", 9) },
            { 24105, ("SpectateFailedMessage", 9) },
            { 24106, ("StopHomeLogicMessage", 9) },
            { 24108, ("MatchmakeFailedMessage", 9) },
            { 24109, ("VisionUpdateMessage", 4) },
            { 24111, ("AvailableServerCommandMessage", 9) },
            { 24112, ("UdpConnectionInfoMessage", 27) },
            { 24113, ("PlayerProfileMessage", 9) },
            { 24114, ("HomeBattleReplayDataMessage", 9) },
            { 24115, ("ServerErrorMessage", 9) },
            { 24116, ("HomeBattleReplayFailedMessage", 9) },
            { 24117, ("HomeBattleReplayViewedMessage", 9) },
            { 24123, ("SeasonRewardsMessage", 9) },
            { 24124, ("TeamMessage", 9) },
            { 24125, ("TeamLeftMessage", 9) },
            { 24129, ("TeamErrorMessage", 9) },
            { 24130, ("TeamGameStartingMessage", 9) },
            { 24131, ("TeamStreamMessage", 11) },
            { 24177, ("SetRegionResponseMessage", 9) },
            { 24178, ("SetCountryResponseMessage", 9) },
            { 24201, ("FacebookAccountBoundMessage", 9) },
            { 24202, ("FacebookAccountAlreadyBoundMessage", 1) },
            { 24203, ("KakaoAccountBoundMessage", 9) },
            { 24204, ("KakaoAccountAlreadyBoundMessage", 1) },
            { 24205, ("LineAccountAlreadyBoundMessage", 1) },
            { 24206, ("LineAccountBoundMessage", 9) },
            { 24214, ("FacebookAccountUnboundMessage", 9) },
            { 24215, ("KakaoAccountUnboundMessage", 9) },
            { 24216, ("LineAccountUnboundMessage", 9) },
            { 24220, ("TencentAccountBoundMessage", 9) },
            { 24221, ("TencentAccountAlreadyBoundMessage", 1) },
            { 24222, ("TencentAntiAddictionInstructionMessage", 1) },
            { 24223, ("TencentCheckCanPayResponseMessage", 1) },
            { 24301, ("AllianceDataMessage", 11) },
            { 24304, ("JoinableAllianceListMessage", 11) },
            { 24308, ("AllianceMemberMessage", 11) },
            { 24309, ("AllianceMemberRemovedMessage", 11) },
            { 24310, ("AllianceListMessage", 11) },
            { 24311, ("AllianceStreamMessage", 11) },
            { 24312, ("AllianceStreamEntryMessage", 11) },
            { 24313, ("ChangeAllianceSettingsOkMessage", 11) },
            { 24318, ("AllianceStreamEntryRemovedMessage", 11) },
            { 24319, ("TeamStreamEntryRemovedMessage", 11) },
            { 24321, ("AllianceInvitationSendFailedMessage", 11) },
            { 24333, ("AllianceResponseMessage", 11) },
            { 24364, ("AllianceTeamsMessage", 11) },
            { 24365, ("AllianceTeamRemovedMessage", 11) },
            { 24399, ("MyAllianceMessage", 11) },
            { 24403, ("LeaderboardMessage", 13) },
            { 24411, ("AvatarStreamMessage", 11) },
            { 24412, ("AvatarStreamEntryMessage", 11) },
            { 24413, ("BattleReportStreamMessage", 11) },
            { 24418, ("AvatarStreamEntryRemovedMessage", 11) },
            { 24555, ("FriendOnlineStatusEntryMessage", 11) },
            { 24582, ("TeamInviteStatusMessage", 23) },
            { 24589, ("TeamInvitationMessage", 9) },
            { 24700, ("BrawlTvChannelListMessage", 33) },
            { 24701, ("BrawlTvChannelNextUpMessage", 33) },
            { 24715, ("GlobalChatLineMessage", 6) },
            { 24758, ("ApiTokenMessage", 9) },
            { 24776, ("AllianceWarMessage", 25) },
            { 24777, ("PlayAgainStatusMessage", 9) },
            { 25165, ("SCIDAccountBoundMessage", 10) },
            { 25892, ("TitanDisconnectedMessage", 1) },
            { 26002, ("LogicDeviceLinkCodeResponseMessage", 1) },
            { 26003, ("LogicDeviceLinkNewDeviceLinkedMessage", 1) },
            { 26004, ("LogicDeviceLinkCodeDeactivatedMessage", 1) },
            { 26005, ("LogicDeviceLinkResponseMessage", 1) },
            { 26007, ("LogicDeviceLinkDoneMessage", 1) },
            { 26008, ("LogicDeviceLinkErrorMessage", 1) },
            { 26085, ("GamecenterAccountBoundMessage", 10) },
            { 27002, ("LogicAccountTransferCodeResponseMessage", 1) },
            { 28363, ("BuyBundleBillingPackResponseMessage", 9) },
            { 28686, ("SetSupportedCreatorResponseMessage", 9) },
            { 28689, ("SCIDAccountAlreadyBoundMessage", 1) },
            { 29001, ("StartLatencyTestRequestMessage", 9) },
            { 29002, ("UdpLatencyTestResponseMessage", 9) },
            { 29003, ("LatencyTestStatusMessage", 9) },
            { 29900, ("SupercellIdNotificationMessage", 9) },
            { 29997, ("CryptoErrorMessage", 1) },
            { 30000, ("AttributionMessage", 9) },
            { 40000, ("AdUpdateConversionValueMessage", 1) },
            { 0, ("FriendAvatarBaseMessage", 26) }
        }.ToFrozenDictionary();

        CommandCollectorX = new Dictionary<string, int>
        {
            { "LogicChangeAvatarNameCommand", 201 },
            { "LogicDiamondsAddedCommand", 202 },
            { "LogicGiveDeliveryItemsCommand", 203 },
            { "LogicDayChangedCommand", 204 },
            { "LogicDecreaseHeroScoreCommand", 205 },
            { "LogicAddNotificationCommand", 206 },
            { "LogicChangeResourcesCommand", 207 },
            { "LogicTransactionsRevokedCommand", 208 },
            { "LogicKeyPoolChangedCommand", 209 },
            { "LogicIAPChangedCommand", 210 },
            { "LogicOffersChangedCommand", 211 },
            { "LogicPlayerDataChangedCommand", 212 },
            { "LogicInviteBlockingChangedCommand", 213 },
            { "LogicGemNameChangeStateChangedCommand", 214 },
            { "LogicSetSupportedCreatorCommand", 215 },
            { "LogicCooldownExpiredCommand", 216 },
            { "LogicProLeagueSeasonChangedCommand", 217 },
            { "LogicBrawlPassSeasonChangedCommand", 218 },
            { "LogicBrawlPassUnlockedCommand", 219 },
            { "LogicHeroWinQuestsChangedCommand", 220 },
            { "LogicTeamChatMuteStateChangedCommand", 221 },
            { "LogicRankedSeasonChangedCommand", 222 },
            { "LogicCooldownAddedCommand", 223 },
            { "LogicSetESportsHubNotificationCommand", 224 },
            { "LogicGatchaCommand", 500 },
            { "LogicClaimDailyRewardCommand", 503 },
            { "LogicSendAllianceMailCommand", 504 },
            { "LogicSetPlayerThumbnailCommand", 505 },
            { "LogicSelectSkinCommand", 506 },
            { "LogicUnlockSkinCommand", 507 },
            { "LogicChangeControlModeCommand", 508 },
            { "LogicPurchaseDoubleCoinsCommand", 509 },
            { "LogicHelpOpenedCommand", 511 },
            { "LogicToggleInGameHintsCommand", 512 },
            { "LogicDeleteNotificationCommand", 514 },
            { "LogicClearShopTickersCommand", 515 },
            { "LogicClaimRankUpRewardCommand", 517 },
            { "LogicPurchaseOfferCommand", 519 },
            { "LogicLevelUpCommand", 520 },
            { "LogicPurchaseHeroLvlUpMaterialCommand", 521 },
            { "LogicHeroSeenCommand", 522 },
            { "LogicClaimAdRewardCommand", 523 },
            { "LogicVideoStartedCommand", 524 },
            { "LogicSelectCharacterCommand", 525 },
            { "LogicUnlockFreeSkinsCommand", 526 },
            { "LogicSetPlayerNameColorCommand", 527 },
            { "LogicViewInboxNotificationCommand", 528 },
            { "LogicSelectStarPowerCommand", 529 },
            { "LogicSetPlayerAgeCommand", 530 },
            { "LogicCancelPurchaseOfferCommand", 531 },
            { "LogicItemSeenCommand", 532 },
            { "LogicQuestsSeenCommand", 533 },
            { "LogicPurchaseBrawlPassCommand", 534 },
            { "LogicClaimTailRewardCommand", 535 },
            { "LogicPurchaseBrawlPassProgressCommand", 536 },
            { "LogicVanityItemSeenCommand", 537 },
            { "LogicSelectEmoteCommand", 538 },
            { "LogicBrawlPassAutoCollectWarningSeenCommand", 539 },
            { "LogicPurchaseChallengeLivesCommand", 540 },
            { "LogicClearESportsHubNotificationCommand", 541 },
            { "LogicSelectGroupSkinCommand", 542 },
            { "LogicDebugCommand", 1000 }
        }.ToFrozenDictionary();

        CommandCollectorY = new Dictionary<int, string>
        {
            { 201, "LogicChangeAvatarNameCommand" },
            { 202, "LogicDiamondsAddedCommand" },
            { 203, "LogicGiveDeliveryItemsCommand" },
            { 204, "LogicDayChangedCommand" },
            { 205, "LogicDecreaseHeroScoreCommand" },
            { 206, "LogicAddNotificationCommand" },
            { 207, "LogicChangeResourcesCommand" },
            { 208, "LogicTransactionsRevokedCommand" },
            { 209, "LogicKeyPoolChangedCommand" },
            { 210, "LogicIAPChangedCommand" },
            { 211, "LogicOffersChangedCommand" },
            { 212, "LogicPlayerDataChangedCommand" },
            { 213, "LogicInviteBlockingChangedCommand" },
            { 214, "LogicGemNameChangeStateChangedCommand" },
            { 215, "LogicSetSupportedCreatorCommand" },
            { 216, "LogicCooldownExpiredCommand" },
            { 217, "LogicProLeagueSeasonChangedCommand" },
            { 218, "LogicBrawlPassSeasonChangedCommand" },
            { 219, "LogicBrawlPassUnlockedCommand" },
            { 220, "LogicHeroWinQuestsChangedCommand" },
            { 221, "LogicTeamChatMuteStateChangedCommand" },
            { 222, "LogicRankedSeasonChangedCommand" },
            { 223, "LogicCooldownAddedCommand" },
            { 224, "LogicSetESportsHubNotificationCommand" },
            { 500, "LogicGatchaCommand" },
            { 503, "LogicClaimDailyRewardCommand" },
            { 504, "LogicSendAllianceMailCommand" },
            { 505, "LogicSetPlayerThumbnailCommand" },
            { 506, "LogicSelectSkinCommand" },
            { 507, "LogicUnlockSkinCommand" },
            { 508, "LogicChangeControlModeCommand" },
            { 509, "LogicPurchaseDoubleCoinsCommand" },
            { 511, "LogicHelpOpenedCommand" },
            { 512, "LogicToggleInGameHintsCommand" },
            { 514, "LogicDeleteNotificationCommand" },
            { 515, "LogicClearShopTickersCommand" },
            { 517, "LogicClaimRankUpRewardCommand" },
            { 519, "LogicPurchaseOfferCommand" },
            { 520, "LogicLevelUpCommand" },
            { 521, "LogicPurchaseHeroLvlUpMaterialCommand" },
            { 522, "LogicHeroSeenCommand" },
            { 523, "LogicClaimAdRewardCommand" },
            { 524, "LogicVideoStartedCommand" },
            { 525, "LogicSelectCharacterCommand" },
            { 526, "LogicUnlockFreeSkinsCommand" },
            { 527, "LogicSetPlayerNameColorCommand" },
            { 528, "LogicViewInboxNotificationCommand" },
            { 529, "LogicSelectStarPowerCommand" },
            { 530, "LogicSetPlayerAgeCommand" },
            { 531, "LogicCancelPurchaseOfferCommand" },
            { 532, "LogicItemSeenCommand" },
            { 533, "LogicQuestsSeenCommand" },
            { 534, "LogicPurchaseBrawlPassCommand" },
            { 535, "LogicClaimTailRewardCommand" },
            { 536, "LogicPurchaseBrawlPassProgressCommand" },
            { 537, "LogicVanityItemSeenCommand" },
            { 538, "LogicSelectEmoteCommand" },
            { 539, "LogicBrawlPassAutoCollectWarningSeenCommand" },
            { 540, "LogicPurchaseChallengeLivesCommand" },
            { 541, "LogicClearESportsHubNotificationCommand" },
            { 542, "LogicSelectGroupSkinCommand" },
            { 1000, "LogicDebugCommand" }
        }.ToFrozenDictionary();
    }
}